export interface Upgrade {
  id: string;
  name: string;
  icon: string;
  description: string;
  flavorText: string;
  baseCost: number;
  clickBonus: number;       // flat click value addition
  cpsBonus: number;         // flat CPS addition
  clickMultiplier: number;  // multiplier on click value (1 = no change)
  cpsMultiplier: number;    // multiplier on all CPS (1 = no change)
  category: "click" | "passive" | "hybrid" | "multiplier";
  requiredCoins?: number;   // minimum total coins earned to show
}

export const UPGRADES: Upgrade[] = [
  {
    id: "better_dough",
    name: "Better Dough",
    icon: "🌾",
    description: "Premium semolina flour gives your dough extra spring.",
    flavorText: "\"The secret is in the flour, not the fingers.\" — Nonna Rosa",
    baseCost: 50,
    clickBonus: 1,
    cpsBonus: 0,
    clickMultiplier: 1,
    cpsMultiplier: 1,
    category: "click",
    requiredCoins: 0,
  },
  {
    id: "fancy_cheese",
    name: "Fancy Cheese",
    icon: "🧀",
    description: "Imported buffalo mozzarella from Naples. Customers lose their minds.",
    flavorText: "Three types of cheese. One legendary pizza.",
    baseCost: 150,
    clickBonus: 2,
    cpsBonus: 0,
    clickMultiplier: 1,
    cpsMultiplier: 1,
    category: "click",
    requiredCoins: 75,
  },
  {
    id: "secret_sauce",
    name: "Secret Sauce",
    icon: "🍅",
    description: "A family recipe passed down through seven generations. Maybe eight.",
    flavorText: "You will never know what's in it. That's the point.",
    baseCost: 500,
    clickBonus: 5,
    cpsBonus: 0,
    clickMultiplier: 1,
    cpsMultiplier: 1,
    category: "click",
    requiredCoins: 200,
  },
  {
    id: "wood_fired_oven",
    name: "Wood-Fired Oven",
    icon: "🔥",
    description: "900°F of pure Italian tradition. Neighbors say the smoke is \"atmospheric.\"",
    flavorText: "Every pizza emerges with those perfect leopard-spot char marks.",
    baseCost: 200,
    clickBonus: 0,
    cpsBonus: 0.5,
    clickMultiplier: 1,
    cpsMultiplier: 1,
    category: "passive",
    requiredCoins: 100,
  },
  {
    id: "delivery_bike",
    name: "Delivery Bike",
    icon: "🚲",
    description: "A vintage Vespa with a hot-box. Thirty minutes or it's free.",
    flavorText: "Luigi once delivered 47 pizzas in a single afternoon. He's a legend.",
    baseCost: 750,
    clickBonus: 0,
    cpsBonus: 1.5,
    clickMultiplier: 1,
    cpsMultiplier: 1,
    category: "passive",
    requiredCoins: 400,
  },
  {
    id: "pizza_robot",
    name: "Pizza Robot",
    icon: "🤖",
    description: "Pneumatically powered dough-slinger. 300 RPM toss speed. Zero sick days.",
    flavorText: "It can't feel love, but it can feel the dough. Close enough.",
    baseCost: 3000,
    clickBonus: 8,
    cpsBonus: 2,
    clickMultiplier: 1,
    cpsMultiplier: 1,
    category: "hybrid",
    requiredCoins: 1500,
  },
  {
    id: "second_location",
    name: "Second Location",
    icon: "🏪",
    description: "A second restaurant on the other side of town. Double the ovens, double the chaos.",
    flavorText: "The landlord said \"You'll be back.\" You are not back.",
    baseCost: 10000,
    clickBonus: 0,
    cpsBonus: 5,
    clickMultiplier: 1,
    cpsMultiplier: 1.2,
    category: "passive",
    requiredCoins: 5000,
  },
  {
    id: "tv_ad",
    name: "TV Ad Campaign",
    icon: "📺",
    description: "Prime-time commercial featuring a dancing pizza slice. Extremely catchy jingle.",
    flavorText: "🎵 Come on down to Pizza Empire, where every bite's a SLAM! 🎵",
    baseCost: 25000,
    clickBonus: 0,
    cpsBonus: 0,
    clickMultiplier: 2,
    cpsMultiplier: 1,
    category: "multiplier",
    requiredCoins: 12000,
  },
  {
    id: "franchise_deal",
    name: "Franchise Deal",
    icon: "📜",
    description: "License the Pizza Empire brand. 50 locations opening this quarter.",
    flavorText: "You have officially become a franchise. Congratulations and condolences.",
    baseCost: 100000,
    clickBonus: 0,
    cpsBonus: 20,
    clickMultiplier: 1,
    cpsMultiplier: 1.5,
    category: "passive",
    requiredCoins: 50000,
  },
  {
    id: "international_chain",
    name: "International Chain",
    icon: "🌍",
    description: "Pizza Empire goes global. 23 countries, 400 locations, one dream.",
    flavorText: "In Tokyo they put mayo on it. You said okay. Sales tripled.",
    baseCost: 500000,
    clickBonus: 20,
    cpsBonus: 50,
    clickMultiplier: 2,
    cpsMultiplier: 2,
    category: "multiplier",
    requiredCoins: 200000,
  },
  {
    id: "drone_delivery",
    name: "Drone Delivery",
    icon: "🚁",
    description: "A fleet of GPS-guided delivery drones. Zero traffic. Infinite skies.",
    flavorText: "Customer complained their pizza was \"too warm.\" It came from the sky.",
    baseCost: 2000000,
    clickBonus: 0,
    cpsBonus: 80,
    clickMultiplier: 1,
    cpsMultiplier: 2,
    category: "passive",
    requiredCoins: 800000,
  },
  {
    id: "space_pizza_lab",
    name: "Space Pizza Lab",
    icon: "🚀",
    description: "Zero-gravity dough. Asteroid-mineral toppings. The final frontier of flavor.",
    flavorText: "Houston, we have a pizza. ETA: 6 minutes.",
    baseCost: 10000000,
    clickBonus: 100,
    cpsBonus: 250,
    clickMultiplier: 3,
    cpsMultiplier: 3,
    category: "multiplier",
    requiredCoins: 4000000,
  },
];

export function getUpgradeById(id: string): Upgrade | undefined {
  return UPGRADES.find((u) => u.id === id);
}
